runtime: custom
env: flex
service: default
threadsafe: yes
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 120 # default value
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 5
# volumes:
# - name: ramdisk1
#   volume_type: tmpfs
#   size_gb: 0.5